name: Jnigi Test
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build docker images
      run: docker build -t jnigi_test .
    - name: Run tests
      run: docker run jnigi_test
